# This dataset contains a list of video games with sales greater than 100,000 copies. It was generated by a scrape of vgchartz.com.
# 
# Fields include
# Rank - Ranking of overall sales
# Name - The games name
# Platform - Platform of the games release (i.e. PC,PS4, etc.)
# Year - Year of the game's release
# Genre - Genre of the game
# Publisher - Publisher of the game
# NA_Sales - Sales in North America (in millions)
# EU_Sales - Sales in Europe (in millions)
# JP_Sales - Sales in Japan (in millions)
# Other_Sales - Sales in the rest of the world (in millions)
# Global_Sales - Total worldwide sales.
#
#
#
#


# Import libraries
library(readr)
library(dplyr)

# Column names
properties <- c("Rank", "Name", "Platform", "Year", "Genre",
                "Publisher", "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales")

# Import vgsales.csv: vgsales
vgsales <- read_csv("vgsales.csv", skip = 1, col_types = "icciccddddd", col_names = properties)

# Call head() on vgsales
head(vgsales)

# Summary
summary(vgsales)

# Size
length = length(vgsales$Year)

# smallest year
smallest_year = min(vgsales$Year, na.rm = TRUE)

# greatest year
greatest_year = max(vgsales$Year, na.rm = TRUE)

# Count video games by year
vg_by_year <- vgsales %>% count(Year)

# Year with most number of games
most_number_of_games_by_year_idx <- which.max(vg_by_year$n)
most_number_of_games_year <- vg_by_year[most_number_of_games_by_year_idx,]

# Year with less number of games
less_number_of_games_by_year_idx <- which.min(vg_by_year$n)
less_number_of_games_year <- vg_by_year[less_number_of_games_by_year_idx,]

# Count video games by genre
vg_by_genre <- vgsales %>% count(Genre)

# Genre with most number of games
most_number_of_games_by_genre_idx <- which.max(vg_by_genre$n)
most_number_of_games_genre <- vg_by_genre[most_number_of_games_by_genre_idx,]

# Genre with less number of games
less_number_of_games_by_genre_idx <- which.min(vg_by_genre$n)
less_number_of_games_by_genre <- vg_by_genre[less_number_of_games_by_genre_idx,]