# This dataset contains a list of video games with sales greater than 100,000 copies. It was generated by a scrape of vgchartz.com.
# 
# Fields include
# Rank - Ranking of overall sales
# Name - The games name
# Platform - Platform of the games release (i.e. PC,PS4, etc.)
# Year - Year of the game's release
# Genre - Genre of the game
# Publisher - Publisher of the game
# NA_Sales - Sales in North America (in millions)
# EU_Sales - Sales in Europe (in millions)
# JP_Sales - Sales in Japan (in millions)
# Other_Sales - Sales in the rest of the world (in millions)
# Global_Sales - Total worldwide sales.
#



# Import libraries
library(readr)
library(dplyr)

# Column names
properties <- c("Rank", "Name", "Platform", "Year", "Genre",
                "Publisher", "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales")

# Import vgsales.csv: raw_vgsales
vgsales <- read_csv("vgsales.csv", skip = 1, col_types = "icciccddddd", col_names = properties)

year_2018 <- 2018 
# Filtering to work with year until 2018, inclusive.
vgsales <- vgsales %>% filter(vgsales$Year <= year_2018)

# Call head() on vgsales
head(vgsales)

# Summary
summary(vgsales)

# Size
length = length(vgsales$Year)

# smallest year
smallest_year = min(vgsales$Year, na.rm = TRUE)

# greatest year
greatest_year = max(vgsales$Year, na.rm = TRUE)

# Count video games by year
vg_by_year <- vgsales %>% count(Year)

# Sorting video games count by year in decreasing order
vg_by_year_in_decreasing_order <- vg_by_year[order(vg_by_year$n, decreasing = TRUE),]

# Year with most number of games
most_number_of_games_by_year_idx <- which.max(vg_by_year$n)
most_number_of_games_year <- vg_by_year[most_number_of_games_by_year_idx,]

# Year with less number of games
less_number_of_games_by_year_idx <- which.min(vg_by_year$n)
less_number_of_games_year <- vg_by_year[less_number_of_games_by_year_idx,]

# Count video games by genre
vg_by_genre <- vgsales %>% count(Genre)

# Sorting video games count by genre in decreasing order
vg_by_genre <- vg_by_genre[order(vg_by_genre$n, decreasing = TRUE),]

# Genre with most number of games
most_number_of_games_by_genre_idx <- which.max(vg_by_genre$n)
most_number_of_games_genre <- vg_by_genre[most_number_of_games_by_genre_idx,]

# Genre with less number of games
less_number_of_games_by_genre_idx <- which.min(vg_by_genre$n)
less_number_of_games_by_genre <- vg_by_genre[less_number_of_games_by_genre_idx,]

# Years with sales
years_with_sales <- sort(unique(vgsales$Year, na.rm = TRUE))

# Years without sales
years_without_sales <- (smallest_year:year_2018)[!(smallest_year:year_2018) %in% years_with_sales]

# Games of 1989
games_of_1989 <- vgsales[vgsales$Year == 1989,]

# Count video games by platform
vg_by_platform <- vgsales %>% count(Platform)

# Platform with most number of games
most_number_of_games_by_platform_idx <- which.max(vg_by_platform$n)
most_number_of_games_platform <- vg_by_platform[most_number_of_games_by_platform_idx,]

# Platform with less number of games
less_number_of_games_by_platform_idx <- which.min(vg_by_platform$n)
less_number_of_games_platform <- vg_by_platform[less_number_of_games_by_platform_idx,]

# Games from Platform GG
games_from_platform_gg <- vgsales[vgsales$Platform == "GG",]$Name


# Count video games by publisher
vg_by_publisher <- vgsales %>% count(Publisher)

# Sorting video games count by publisher in decreasing order
vg_by_publisher <- vg_by_publisher[order(vg_by_publisher$n, decreasing = TRUE),]

# Video Game by Publisher Summary
summary(vg_by_publisher)

# Count North America video games sales by year
# NA_Sales - Sales in North America (in millions)
north_america_vg_sales_by_year <- aggregate(vgsales$NA_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)

# Count European video games sales by year
# EU_Sales - Sales in Europe (in millions)
europe_vg_sales_by_year <- aggregate(vgsales$EU_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)

# Count Japan video games sales by year
# JP_Sales - Sales in Japan (in millions)
japan_vg_sales_by_year <- aggregate(vgsales$JP_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)

# Count Other Location video games sales by year
# Other_Sales - Sales in Other locations (in millions)
other_locations_vg_sales_by_year <- aggregate(vgsales$Other_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)