# This dataset contains a list of video games with sales greater than 100,000 copies. It was generated by a scrape of vgchartz.com.
# 
# Fields include
# Rank - Ranking of overall sales
# Name - The games name
# Platform - Platform of the games release (i.e. PC,PS4, etc.)
# Year - Year of the game's release
# Genre - Genre of the game
# Publisher - Publisher of the game
# NA_Sales - Sales in North America (in millions)
# EU_Sales - Sales in Europe (in millions)
# JP_Sales - Sales in Japan (in millions)
# Other_Sales - Sales in the rest of the world (in millions)
# Global_Sales - Total worldwide sales.
#



# Import libraries
library(readr)
library(dplyr)

# Column names
properties <- c("Rank", "Name", "Platform", "Year", "Genre",
                "Publisher", "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales")

# Import vgsales.csv: raw_vgsales
vgsales <- read_csv("vgsales.csv", skip = 1, col_types = "icfiffddddd", col_names = properties)

year_2018 <- 2018 
# Filtering to work with year until 2018, inclusive.
vgsales <- vgsales %>% filter(vgsales$Year <= year_2018)

# A good practice when you import a dataset is to use the glimpse() function to have an idea about the structure of the dataset.
# Structure of the data
glimpse(vgsales)

# Call head() on vgsales
head(vgsales)

# Summary
summary(vgsales)

# Size
length = length(vgsales$Year)

# smallest year
smallest_year = min(vgsales$Year, na.rm = TRUE)

# greatest year
greatest_year = max(vgsales$Year, na.rm = TRUE)

# Count video games by year
vg_by_year <- vgsales %>% count(Year)

# Sorting video games count by year in decreasing order
vg_by_year_in_decreasing_order <- vg_by_year[order(vg_by_year$n, decreasing = TRUE),]

# Year with most number of games
most_number_of_games_by_year_idx <- which.max(vg_by_year$n)
most_number_of_games_year <- vg_by_year[most_number_of_games_by_year_idx,]

# Year with less number of games
less_number_of_games_by_year_idx <- which.min(vg_by_year$n)
less_number_of_games_year <- vg_by_year[less_number_of_games_by_year_idx,]

# Count video games by genre
vg_by_genre <- vgsales %>% count(Genre)

# Sorting video games count by genre in decreasing order
vg_by_genre <- vg_by_genre[order(vg_by_genre$n, decreasing = TRUE),]

# Genre with most number of games
most_number_of_games_by_genre_idx <- which.max(vg_by_genre$n)
most_number_of_games_genre <- vg_by_genre[most_number_of_games_by_genre_idx,]

# Genre with less number of games
less_number_of_games_by_genre_idx <- which.min(vg_by_genre$n)
less_number_of_games_by_genre <- vg_by_genre[less_number_of_games_by_genre_idx,]

# Years with sales
years_with_sales <- sort(unique(vgsales$Year, na.rm = TRUE))

# Years without sales
years_without_sales <- (smallest_year:year_2018)[!(smallest_year:year_2018) %in% years_with_sales]

# Games of 1989
games_of_1989 <- vgsales[vgsales$Year == 1989,]

# Count video games by platform
vg_by_platform <- vgsales %>% count(Platform)

# Platform with most number of games
most_number_of_games_by_platform_idx <- which.max(vg_by_platform$n)
most_number_of_games_platform <- vg_by_platform[most_number_of_games_by_platform_idx,]

# Platform with less number of games
less_number_of_games_by_platform_idx <- which.min(vg_by_platform$n)
less_number_of_games_platform <- vg_by_platform[less_number_of_games_by_platform_idx,]

# Games from Platform GG
games_from_platform_gg <- vgsales[vgsales$Platform == "GG",]$Name


# Count video games by publisher
vg_by_publisher <- vgsales %>% count(Publisher)

# Sorting video games count by publisher in decreasing order
vg_by_publisher <- vg_by_publisher[order(vg_by_publisher$n, decreasing = TRUE),]

# Video Game by Publisher Summary
summary(vg_by_publisher)

# Count North America video games sales by year
# NA_Sales - Sales in North America (in millions)
north_america_vg_sales_by_year <- aggregate(vgsales$NA_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)

# Count European video games sales by year
# EU_Sales - Sales in Europe (in millions)
europe_vg_sales_by_year <- aggregate(vgsales$EU_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)

# Count Japan video games sales by year
# JP_Sales - Sales in Japan (in millions)
japan_vg_sales_by_year <- aggregate(vgsales$JP_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)

# Count Other Location video games sales by year
# Other_Sales - Sales in Other locations (in millions)
other_locations_vg_sales_by_year <- aggregate(vgsales$Other_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)

# Count Global video games sales by year
# Global_Sales - Sales in Global (in millions)
global_vg_sales_by_year <- aggregate(vgsales$Global_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)



# Correlations
#
# Excursion: Correlation
# If you're familiar with statistics, you'll have heard about Pearson's Correlation. 
# It is a measurement to evaluate the linear dependency between two variables, say X and Y. 
# It can range from -1 to 1; if it's close to 1 it means that there is a strong positive association between the variables. 
# If X is high, also Y tends to be high. If it's close to -1, there is a strong negative association: If X is high, Y tends to be low. 
# When the Pearson correlation between two variables is 0, these variables are possibly independent: there is no association between X and Y.
#
# You can calculate the correlation between two vectors with the cor() function. 
# Take this code for example, that computes the correlation between the columns height and width of a fictional data frame size:
#
# cor(size$height, size$width)
# The data you've worked with in the previous exercise, international.sav, is again available in your working directory. 
# It's now up to import it and undertake the correct calculations to answer the following question:
#
#
#
# Correlation between Global and North America Sales
cor(global_vg_sales_by_year, north_america_vg_sales_by_year)

# Correlation between Global and Europe Sales
cor(global_vg_sales_by_year, europe_vg_sales_by_year)

# Correlation between Global and Japan Sales
cor(global_vg_sales_by_year,japan_vg_sales_by_year)

# Correlation between Global and Other Countries Sales
cor(global_vg_sales_by_year, other_locations_vg_sales_by_year)

# Correlation between North America and Europe Sales
cor(north_america_vg_sales_by_year, europe_vg_sales_by_year)

# Correlation between North America and Japan Sales
cor(north_america_vg_sales_by_year, japan_vg_sales_by_year)

# Correlation between North America and Other Countries Sales
cor(north_america_vg_sales_by_year, other_locations_vg_sales_by_year)

# Correlation between Europe and Japan Sales
cor(europe_vg_sales_by_year, japan_vg_sales_by_year)

# Correlation between Europe and Other Countries Sales
cor(europe_vg_sales_by_year, other_locations_vg_sales_by_year)

# Correlation between Japan and Other Countries Sales
cor(japan_vg_sales_by_year, other_locations_vg_sales_by_year)



# Count video games by platform per year
vg_sales_by_year <- aggregate(vgsales$Global_Sales, by=list(Year=vgsales$Year), FUN=sum) %>% group_by(Year)

# Sport games
# Filter genre sports and platform wii
sports_wii <- vgsales[vgsales$Genre == "Sports" & vgsales$Platform == "Wii",]

# Count wii sports sales grouped by year
wii_sports_by_year = aggregate(sports_wii$NA_Sales, by=list(Year=sports_wii$Year), FUN=sum) %>% group_by(Year)

# Plot Wii Sport data grouped by year
plot(wii_sports_by_year)

# Filter genre sports
sports_vgsales <- vgsales[vgsales$Genre == "Sports",]

# Count sports sales grouped by year
sports_by_year = aggregate(sports_vgsales$NA_Sales, by=list(Year=sports_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot Sport data grouped by year
plot(sports_by_year)


# Filter genre action
action_vgsales <- vgsales[vgsales$Genre == "Action",]

# Count action sales grouped by year
action_by_year = aggregate(action_vgsales$NA_Sales, by=list(Year=action_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot action data grouped by year
plot(action_by_year)


# Filter genre misc
misc_vgsales <- vgsales[vgsales$Genre == "Misc",]

# Count misc sales grouped by year
misc_by_year = aggregate(misc_vgsales$NA_Sales, by=list(Year=misc_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot misc data grouped by year
plot(misc_by_year)


# Filter genre Role-Playing
rpg_vgsales <- vgsales[vgsales$Genre == "Role-Playing",]

# Count rpg sales grouped by year
rpg_by_year = aggregate(rpg_vgsales$NA_Sales, by=list(Year=rpg_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot rpg data grouped by year
plot(rpg_by_year)


# Filter genre Shooter
shooter_vgsales <- vgsales[vgsales$Genre == "Shooter",]

# Count shooter sales grouped by year
shooter_by_year = aggregate(shooter_vgsales$NA_Sales, by=list(Year=shooter_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot shooter data grouped by year
plot(shooter_by_year)


# Filter genre Adventure
adventure_vgsales <- vgsales[vgsales$Genre == "Adventure",]

# Count adventure sales grouped by year
adventure_by_year = aggregate(adventure_vgsales$NA_Sales, by=list(Year=adventure_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot adventure data grouped by year
plot(adventure_by_year)


# Filter genre Racing
racing_vgsales <- vgsales[vgsales$Genre == "Racing",]

# Count racing sales grouped by year
racing_by_year = aggregate(racing_vgsales$NA_Sales, by=list(Year=racing_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot racing data grouped by year
plot(racing_by_year)


# Filter genre Platform
platform_vgsales <- vgsales[vgsales$Genre == "Platform",]

# Count platform sales grouped by year
platform_by_year = aggregate(platform_vgsales$NA_Sales, by=list(Year=platform_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot platform data grouped by year
plot(platform_by_year)


# Filter genre Simulation
simulation_vgsales <- vgsales[vgsales$Genre == "Simulation",]

# Count simulation sales grouped by year
simulation_by_year = aggregate(simulation_vgsales$NA_Sales, by=list(Year=simulation_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot simulation data grouped by year
plot(simulation_by_year)


# Filter genre Fighting
fighting_vgsales <- vgsales[vgsales$Genre == "Fighting",]

# Count fighting sales grouped by year
fighting_by_year = aggregate(fighting_vgsales$NA_Sales, by=list(Year=fighting_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot fighting data grouped by year
plot(fighting_by_year)


# Filter genre Strategy
strategy_vgsales <- vgsales[vgsales$Genre == "Strategy",]

# Count strategy sales grouped by year
strategy_by_year = aggregate(strategy_vgsales$NA_Sales, by=list(Year=strategy_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot strategy data grouped by year
plot(strategy_by_year)


# Filter genre Puzzle
puzzle_vgsales <- vgsales[vgsales$Genre == "Puzzle",]

# Count puzzle sales grouped by year
puzzle_by_year = aggregate(puzzle_vgsales$NA_Sales, by=list(Year=puzzle_vgsales$Year), FUN=sum) %>% group_by(Year)

# Plot puzzle data grouped by year
plot(puzzle_by_year)


#
# Analyse period in the console releases
# https://pt.wikipedia.org/wiki/Lista_de_consoles_de_videogame
#

Year = smallest_year:greatest_year
x = 0
empty_table = data.frame(Year, x)
empty_table <- as_tibble(empty_table)


# Filling action by year
action_missing <- empty_table %>% filter(!Year %in% action_by_year$Year)
action_by_year_filled <- bind_rows(action_by_year, action_missing)

# Filling puzzle by year
puzzle_missing <- empty_table %>% filter(!Year %in% puzzle_by_year$Year)
puzzle_by_year_filled <- bind_rows(puzzle_by_year, puzzle_missing)

